pipeline {
  agent {
    docker {
      image 'abhishekf5/maven-abhishek-docker-agent:v1'
      args '--user root -v /var/run/docker.sock:/var/run/docker.sock --add-host=host.docker.internal:host-gateway --dns 8.8.8.8'
    }
  }
  
  environment {
    APP_DIR = 'java-maven-sonar-argocd-helm-k8s/spring-boot-app'
    MANIFEST_DIR = 'java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests'
    SONAR_URL = "http://host.docker.internal:9000"
  }
  
  stages {
    stage('Clean Workspace') {
      steps {
        cleanWs()
      }
    }
    
    stage('Checkout') {
      steps {
        checkout([$class: 'GitSCM', 
          branches: [[name: 'main']],
          userRemoteConfigs: [[url: 'https://github.com/Hetpatel7131/Jenkins-Zero-To-Hero.git']],
          extensions: [[$class: 'CleanBeforeCheckout']]
        ])
      }
    }
    
    stage('Build and Test') {
      steps {
        retry(3) {
          sh """
            cd ${APP_DIR} && \
            mvn clean package -U -B
          """
        }
      }
    }
    
    // ... rest of your pipeline stages ...
  }
  
  post {
    always {
      echo "Build ${currentBuild.currentResult} - ${BUILD_URL}"
    }
  }
}
