pipeline {
  agent {
    docker {
      image 'abhishekf5/maven-abhishek-docker-agent:v1'
      args '--user root -v /var/run/docker.sock:/var/run/docker.sock --dns 8.8.8.8 --dns 8.8.4.4'
    }
  }
  
  environment {
    APP_DIR = 'java-maven-sonar-argocd-helm-k8s/spring-boot-app'
    MANIFEST_DIR = 'java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests'
  }
  
  stages {
    stage('Checkout') {
      steps {
        checkout([$class: 'GitSCM', 
          branches: [[name: 'main']],
          userRemoteConfigs: [[url: 'https://github.com/Hetpatel7131/Jenkins-Zero-To-Hero.git']]
        ])
      }
    }
    
    stage('Build and Test') {
      steps {
        retry(3) {
          sh """
            cd ${APP_DIR} && \
            mvn clean package -U -B -DskipTests
          """
        }
      }
      post {
        success {
          archiveArtifacts artifacts: "${APP_DIR}/target/*.jar", fingerprint: true
        }
      }
    }
    
    stage('Static Code Analysis') {
      environment {
        SONAR_URL = "http://localhost:9000"
      }
      steps {
        withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
          sh """
            cd ${APP_DIR} && \
            mvn sonar:sonar \
              -Dsonar.login=$SONAR_AUTH_TOKEN \
              -Dsonar.host.url=${SONAR_URL} \
              -Dsonar.projectVersion=${BUILD_NUMBER}
          """
        }
      }
    }
    
    stage('Build and Push Docker Image') {
      environment {
        DOCKER_IMAGE = "hetpatel7131/ultimate-cicd:${BUILD_NUMBER}"
        DOCKERFILE_LOCATION = "${APP_DIR}/Dockerfile"
      }
      steps {
        script {
          withCredentials([usernamePassword(
            credentialsId: 'docker-cred',
            usernameVariable: 'DOCKER_USER',
            passwordVariable: 'DOCKER_PASS'
          )]) {
            sh """
              cd ${APP_DIR} && \
              docker build -t ${DOCKER_IMAGE} -f ${DOCKERFILE_LOCATION} .
            """
            
            sh "echo ${DOCKER_PASS} | docker login -u ${DOCKER_USER} --password-stdin"
            sh "docker push ${DOCKER_IMAGE}"
          }
        }
      }
    }
    
    stage('Update Deployment File') {
      environment {
        GIT_REPO = "https://github.com/Hetpatel7131/Jenkins-Zero-To-Hero.git"
      }
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'github',
          usernameVariable: 'GIT_USER',
          passwordVariable: 'GIT_TOKEN'
        )]) {
          sh """
            git config --global user.email "hetpatel7131@gmail.com"
            git config --global user.name "Jenkins CI"
            
            cd ${MANIFEST_DIR} && \
            sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" deployment.yml
            
            git add deployment.yml
            git commit -m "Update deployment to version ${BUILD_NUMBER}"
            
            git push https://${GIT_USER}:${GIT_TOKEN}@github.com/Hetpatel7131/Jenkins-Zero-To-Hero.git HEAD:main
          """
        }
      }
    }
  }
  
  post {
    failure {
      slackSend channel: '#builds',
                message: "Build ${BUILD_NUMBER} failed: ${BUILD_URL}"
    }
    success {
      slackSend channel: '#builds',
                message: "Build ${BUILD_NUMBER} succeeded: ${BUILD_URL}"
    }
  }
}
